-- ============================================================
--  ~/.config/hypr/colors.lua
--  AUTO-GENERATED by matugen — do not edit manually
-- ============================================================

return {
    active_border   = { colors = { "rgba(ffb4a5ff)", "rgba(dcc48cff)" }, angle = 45 },
    inactive_border = "rgba(534340ff)",
}
