-- ============================================================
--  ~/.config/hypr/colors.lua
--  AUTO-GENERATED by matugen — do not edit manually
-- ============================================================

return {
    active_border   = { colors = { "rgba(8ad6b7ff)", "rgba(a6cce0ff)" }, angle = 45 },
    inactive_border = "rgba(404944ff)",
}
