#!/usr/bin/env bash
# ============================================================
#  setup-dotfiles.sh
#  Run this on your CURRENT system to collect all configs
#  into the dotfiles/ directory ready for the installer
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES="$SCRIPT_DIR/dotfiles"

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[✓]${NC} $*"; }
info() { echo -e "${BLUE}[i]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }

echo -e "${BLUE}Collecting dotfiles from current system...${NC}"
echo ""

# ── Hyprland ──────────────────────────────────────────────────
info "Collecting Hyprland..."
mkdir -p "$DOTFILES/hypr"
cp ~/.config/hypr/hyprland.lua        "$DOTFILES/hypr/" 2>/dev/null && log "hyprland.lua" || warn "hyprland.lua not found"
cp ~/.config/hypr/hyprlock.conf       "$DOTFILES/hypr/" 2>/dev/null && log "hyprlock.conf" || warn "hyprlock.conf not found"
cp ~/.config/hypr/colors.lua          "$DOTFILES/hypr/" 2>/dev/null && log "colors.lua" || warn "colors.lua not found"
cp ~/.config/hypr/wallpaper.sh        "$DOTFILES/hypr/" 2>/dev/null && log "wallpaper.sh" || warn "wallpaper.sh not found"
cp ~/.config/hypr/keybinds-popup.sh   "$DOTFILES/hypr/" 2>/dev/null && log "keybinds-popup.sh" || warn "keybinds-popup.sh not found"

# ── Waybar ────────────────────────────────────────────────────
info "Collecting Waybar..."
mkdir -p "$DOTFILES/waybar"
cp ~/.config/waybar/config.jsonc  "$DOTFILES/waybar/" 2>/dev/null && log "config.jsonc" || warn "config.jsonc not found"
cp ~/.config/waybar/style.css     "$DOTFILES/waybar/" 2>/dev/null && log "style.css" || warn "style.css not found"

# ── Rofi ──────────────────────────────────────────────────────
info "Collecting Rofi..."
mkdir -p "$DOTFILES/rofi"
cp ~/.config/rofi/config.rasi  "$DOTFILES/rofi/" 2>/dev/null && log "config.rasi" || warn "config.rasi not found"
cp ~/.config/rofi/theme.rasi   "$DOTFILES/rofi/" 2>/dev/null && log "theme.rasi" || warn "theme.rasi not found"

# ── Kitty ─────────────────────────────────────────────────────
info "Collecting Kitty..."
mkdir -p "$DOTFILES/kitty"
cp ~/.config/kitty/kitty.conf   "$DOTFILES/kitty/" 2>/dev/null && log "kitty.conf" || warn "kitty.conf not found"
# Create empty colors.conf as placeholder (gets generated by matugen)
touch "$DOTFILES/kitty/colors.conf"
log "colors.conf (placeholder)"

# ── Dunst ─────────────────────────────────────────────────────
info "Collecting Dunst..."
mkdir -p "$DOTFILES/dunst"
cp ~/.config/dunst/dunstrc  "$DOTFILES/dunst/" 2>/dev/null && log "dunstrc" || warn "dunstrc not found"

# ── wlogout ───────────────────────────────────────────────────
info "Collecting wlogout..."
mkdir -p "$DOTFILES/wlogout"
cp ~/.config/wlogout/layout     "$DOTFILES/wlogout/" 2>/dev/null && log "layout" || warn "layout not found"
cp ~/.config/wlogout/style.css  "$DOTFILES/wlogout/" 2>/dev/null && log "style.css" || warn "style.css not found"

# ── Matugen ───────────────────────────────────────────────────
info "Collecting Matugen..."
mkdir -p "$DOTFILES/matugen/templates"
cp ~/.config/matugen/config.toml      "$DOTFILES/matugen/" 2>/dev/null && log "config.toml" || warn "config.toml not found"
cp ~/.config/matugen/templates/*.css  "$DOTFILES/matugen/templates/" 2>/dev/null && log "CSS templates" || warn "CSS templates not found"
cp ~/.config/matugen/templates/*.lua  "$DOTFILES/matugen/templates/" 2>/dev/null && log "Lua templates" || warn "Lua templates not found"
cp ~/.config/matugen/templates/*.conf "$DOTFILES/matugen/templates/" 2>/dev/null && log "Conf templates" || warn "Conf templates not found"
cp ~/.config/matugen/templates/*.rasi "$DOTFILES/matugen/templates/" 2>/dev/null && log "Rasi templates" || warn "Rasi templates not found"

# ── GTK ───────────────────────────────────────────────────────
info "Collecting GTK..."
mkdir -p "$DOTFILES/gtk-3.0" "$DOTFILES/gtk-4.0"
cp ~/.config/gtk-3.0/gtk.css  "$DOTFILES/gtk-3.0/" 2>/dev/null && log "gtk-3.0/gtk.css" || warn "gtk-3.0/gtk.css not found"
cp ~/.config/gtk-4.0/gtk.css  "$DOTFILES/gtk-4.0/" 2>/dev/null && log "gtk-4.0/gtk.css" || warn "gtk-4.0/gtk.css not found"

# ── Neovim ────────────────────────────────────────────────────
info "Collecting Neovim..."
mkdir -p "$DOTFILES/nvim/lua/core" \
         "$DOTFILES/nvim/lua/plugins" \
         "$DOTFILES/nvim/lua/themes" \
         "$DOTFILES/nvim/colors"
cp ~/.config/nvim/init.lua                       "$DOTFILES/nvim/" 2>/dev/null && log "init.lua" || warn "init.lua not found"
cp ~/.config/nvim/lua/core/options.lua           "$DOTFILES/nvim/lua/core/" 2>/dev/null && log "options.lua" || warn "options.lua not found"
cp ~/.config/nvim/lua/core/keymaps.lua           "$DOTFILES/nvim/lua/core/" 2>/dev/null && log "keymaps.lua" || warn "keymaps.lua not found"
cp ~/.config/nvim/lua/core/autocmds.lua          "$DOTFILES/nvim/lua/core/" 2>/dev/null && log "autocmds.lua" || warn "autocmds.lua not found"
cp ~/.config/nvim/lua/plugins/init.lua           "$DOTFILES/nvim/lua/plugins/" 2>/dev/null && log "plugins/init.lua" || warn "plugins/init.lua not found"
cp ~/.config/nvim/colors/matugen.lua             "$DOTFILES/nvim/colors/" 2>/dev/null && log "matugen.lua" || warn "matugen.lua not found"
cp ~/.config/nvim/lua/themes/matugen_colors.lua  "$DOTFILES/nvim/lua/themes/" 2>/dev/null && log "matugen_colors.lua" || warn "matugen_colors.lua not found"

# ── SDDM theme ────────────────────────────────────────────────
info "Collecting SDDM theme..."
mkdir -p "$DOTFILES/sddm-retro"
sudo cp /usr/share/sddm/themes/retro-warm/Main.qml          "$DOTFILES/sddm-retro/" 2>/dev/null && log "Main.qml" || warn "Main.qml not found"
sudo cp /usr/share/sddm/themes/retro-warm/metadata.desktop  "$DOTFILES/sddm-retro/" 2>/dev/null && log "metadata.desktop" || warn "metadata.desktop not found"
sudo chown "$USER:$USER" "$DOTFILES/sddm-retro/"*

# Create theme.conf template (colours get filled by matugen)
cat > "$DOTFILES/sddm-retro/theme.conf" << 'EOF'
[General]
background=background.png
ScreenWidth=1920
ScreenHeight=1080
Font=JetBrainsMono Nerd Font
FontSize=13
EOF
log "theme.conf (template)"

# ── Plymouth theme ────────────────────────────────────────────
info "Collecting Plymouth theme..."
mkdir -p "$DOTFILES/plymouth"
sudo cp /usr/share/plymouth/themes/retro-warm/retro-warm.plymouth  "$DOTFILES/plymouth/" 2>/dev/null && log "retro-warm.plymouth" || warn "retro-warm.plymouth not found"
sudo cp /usr/share/plymouth/themes/retro-warm/retro-warm.script    "$DOTFILES/plymouth/" 2>/dev/null && log "retro-warm.script" || warn "retro-warm.script not found"
sudo cp /usr/share/plymouth/themes/retro-warm/logo.png             "$DOTFILES/plymouth/" 2>/dev/null && log "logo.png" || warn "logo.png not found"
sudo cp /usr/share/plymouth/themes/retro-warm/progress_bar.png     "$DOTFILES/plymouth/" 2>/dev/null && log "progress_bar.png" || warn "progress_bar.png not found"
sudo cp /usr/share/plymouth/themes/retro-warm/progress_box.png     "$DOTFILES/plymouth/" 2>/dev/null && log "progress_box.png" || warn "progress_box.png not found"
sudo chown "$USER:$USER" "$DOTFILES/plymouth/"* 2>/dev/null || true

# ── Default wallpaper ─────────────────────────────────────────
info "Collecting default wallpaper..."
mkdir -p "$DOTFILES/wallpaper"
if [[ -f ~/Pictures/Wallpapers/main.png ]]; then
    cp ~/Pictures/Wallpapers/main.png "$DOTFILES/wallpaper/default.png"
    log "default.png"
elif [[ -f ~/Pictures/Wallpapers/main.jpg ]]; then
    cp ~/Pictures/Wallpapers/main.jpg "$DOTFILES/wallpaper/default.png"
    log "default.png (converted from jpg)"
else
    warn "No wallpaper found at ~/Pictures/Wallpapers/main.png"
    warn "Please copy a wallpaper to $DOTFILES/wallpaper/default.png"
fi

# ── Summary ───────────────────────────────────────────────────
echo ""
echo -e "${GREEN}Dotfiles collected successfully!${NC}"
echo ""
echo "Next steps:"
echo "  1. Review the dotfiles/ directory"
echo "  2. Push to GitHub:"
echo "     git init && git add . && git commit -m 'Initial dotfiles'"
echo "     git remote add origin https://github.com/yourusername/hyprland-dotfiles"
echo "     git push -u origin main"
echo "  3. On a fresh Arch install:"
echo "     git clone https://github.com/yourusername/hyprland-dotfiles"
echo "     cd hyprland-dotfiles && bash install.sh"
echo ""
