-- ============================================================
--  ~/.config/nvim/lua/themes/matugen_colors.lua
--  AUTO-GENERATED by matugen — do not edit manually
--  Edit the template at ~/.config/matugen/templates/nvim-colors.lua
-- ============================================================

return {
    -- Material You palette
    primary           = "#ffb4a5",
    on_primary        = "#561f14",
    primary_container = "#733428",
    secondary         = "#e7bdb4",
    on_secondary      = "#442a24",
    tertiary          = "#dcc48c",
    on_tertiary       = "#3d2f04",
    error             = "#ffb4ab",
    on_error          = "#690005",
    background        = "#1a1110",
    on_background     = "#f1dfdb",
    surface           = "#1a1110",
    on_surface        = "#f1dfdb",
    surface_variant   = "#534340",
    on_surface_variant= "#d8c2bd",
    outline           = "#a08c88",
    outline_variant   = "#534340",
    inverse_surface   = "#f1dfdb",
    inverse_on_surface= "#392e2c",
    inverse_primary   = "#904b3d",
}
