-- ============================================================
--  ~/.config/nvim/lua/themes/matugen_colors.lua
--  AUTO-GENERATED by matugen — do not edit manually
--  Edit the template at ~/.config/matugen/templates/nvim-colors.lua
-- ============================================================

return {
    -- Material You palette
    primary           = "#8ad6b7",
    on_primary        = "#003828",
    primary_container = "#00513c",
    secondary         = "#b3ccbf",
    on_secondary      = "#1e352c",
    tertiary          = "#a6cce0",
    on_tertiary       = "#0a3545",
    error             = "#ffb4ab",
    on_error          = "#690005",
    background        = "#0f1512",
    on_background     = "#dee4df",
    surface           = "#0f1512",
    on_surface        = "#dee4df",
    surface_variant   = "#404944",
    on_surface_variant= "#bfc9c2",
    outline           = "#89938d",
    outline_variant   = "#404944",
    inverse_surface   = "#dee4df",
    inverse_on_surface= "#2c322e",
    inverse_primary   = "#1a6b52",
}
