-- ============================================================
--  ~/.config/nvim/lua/themes/matugen_colors.lua
--  AUTO-GENERATED by matugen — do not edit manually
--  Edit the template at ~/.config/matugen/templates/nvim-colors.lua
-- ============================================================

return {
    -- Material You palette
    primary           = "{{colors.primary.default.hex}}",
    on_primary        = "{{colors.on_primary.default.hex}}",
    primary_container = "{{colors.primary_container.default.hex}}",
    secondary         = "{{colors.secondary.default.hex}}",
    on_secondary      = "{{colors.on_secondary.default.hex}}",
    tertiary          = "{{colors.tertiary.default.hex}}",
    on_tertiary       = "{{colors.on_tertiary.default.hex}}",
    error             = "{{colors.error.default.hex}}",
    on_error          = "{{colors.on_error.default.hex}}",
    background        = "{{colors.background.default.hex}}",
    on_background     = "{{colors.on_background.default.hex}}",
    surface           = "{{colors.surface.default.hex}}",
    on_surface        = "{{colors.on_surface.default.hex}}",
    surface_variant   = "{{colors.surface_variant.default.hex}}",
    on_surface_variant= "{{colors.on_surface_variant.default.hex}}",
    outline           = "{{colors.outline.default.hex}}",
    outline_variant   = "{{colors.outline_variant.default.hex}}",
    inverse_surface   = "{{colors.inverse_surface.default.hex}}",
    inverse_on_surface= "{{colors.inverse_on_surface.default.hex}}",
    inverse_primary   = "{{colors.inverse_primary.default.hex}}",
}
